safe_board_homepage:
    path:     /
    defaults: { _controller: SafeBoardBundle:Default:index }
add:
    path:     /add
    defaults: { _controller: SafeBoardBundle:Association:add }

get_all_associations:
    path:     /getAllAssociations
    defaults: { _controller: SafeBoardBundle:Association:getAllAssociations }

get_association:
    path:     /getAssociation/{id}
    defaults: { _controller: SafeBoardBundle:Association:getAssociation }

update_association:
    path:     /updateAssociation/{id}
    defaults: { _controller: SafeBoardBundle:Association:updateAssociation }

delete:
    path:     /delete/{id}
    defaults: { _controller: SafeBoardBundle:Association:delete }

